// @ts-check
// owns-check rules (docs/plan/waves.md, «Política de archivos compartidos», rule 3). Pure: no git, no file system.
// A card PR fails when it touches a path outside its owns, a frozen file whose editableBy does not list the card,
// makes a non-append change to an append-only file, or comes from an unknown card id. renovate/ and opus/ are exempt.

/** @typedef {{ id: string, owns: string[] }} CardEntry */
/** @typedef {{ path: string, editableBy: string[] }} FrozenEntry */
/** @typedef {{ status: string, path: string }} ChangedFile */
/** @typedef {{ kind: 'card', cardId: string } | { kind: 'exempt', prefix: string } | { kind: 'invalid' }} BranchInfo */
/** @typedef {{ outcome: 'pass' | 'fail' | 'exempt', cardId: string | null, violations: string[] }} OwnsCheckResult */
/**
 * @typedef {object} EvaluateInput
 * @property {string} branch the PR head branch
 * @property {ChangedFile[]} changes files changed between the merge-base and the head
 * @property {Map<string, CardEntry>} cards from docs/plan/cards.json (parseCards)
 * @property {FrozenEntry[]} frozen from docs/plan/frozen-files.json (parseFrozenFiles)
 * @property {(path: string) => string | null} readBefore file content at the merge-base, null if absent
 * @property {(path: string) => string | null} readAfter file content at the head, null if absent
 */

export const CARDS_FILE = 'docs/plan/cards.json';
export const FROZEN_FILES_FILE = 'docs/plan/frozen-files.json';
export const EXEMPT_BRANCH_PREFIXES = ['renovate/', 'opus/'];
/** JSON arrays that may only gain entries at the end (tools/conformance/enforced-features.json: only new tags). */
export const APPEND_ONLY_FILES = ['tools/conformance/enforced-features.json'];

const CARD_BRANCH = /^card\/(W\d+-\d{2,})-[a-z0-9]+(?:-[a-z0-9]+)*$/;

/** Invalid docs/plan/cards.json or docs/plan/frozen-files.json. */
export class OwnsCheckConfigError extends Error {
  /** @param {string} message */
  constructor(message) {
    super(message);
    this.name = 'OwnsCheckConfigError';
  }
}

/**
 * @param {string} branch
 * @returns {BranchInfo}
 */
export function parseBranch(branch) {
  const prefix = EXEMPT_BRANCH_PREFIXES.find((candidate) => branch.startsWith(candidate));
  if (prefix !== undefined) return { kind: 'exempt', prefix };
  const match = CARD_BRANCH.exec(branch);
  return match ? { kind: 'card', cardId: match[1] ?? '' } : { kind: 'invalid' };
}

/**
 * A pattern ending in "/" matches every path below it; any other pattern matches one exact path.
 * @param {string} pattern
 * @param {string} path
 * @returns {boolean}
 */
export function pathMatches(pattern, path) {
  return pattern.endsWith('/') ? path.startsWith(pattern) : path === pattern;
}

/**
 * @param {string} text
 * @param {string} file
 * @returns {unknown}
 */
function parseJson(text, file) {
  try {
    return JSON.parse(text);
  } catch {
    throw new OwnsCheckConfigError(`${file}: invalid JSON`);
  }
}

/**
 * @param {unknown} value
 * @returns {value is string[]}
 */
function isStringList(value) {
  return Array.isArray(value) && value.every((item) => typeof item === 'string');
}

/**
 * Parses docs/plan/cards.json (generated by tools/plan/render_plan.py) into card id → entry.
 * @param {string} text
 * @returns {Map<string, CardEntry>}
 */
export function parseCards(text) {
  const data = parseJson(text, CARDS_FILE);
  if (!Array.isArray(data)) throw new OwnsCheckConfigError(`${CARDS_FILE}: expected a JSON array of cards`);
  /** @type {Map<string, CardEntry>} */
  const cards = new Map();
  data.forEach((entry, index) => {
    const id = entry?.id;
    if (typeof id !== 'string' || id === '') throw new OwnsCheckConfigError(`${CARDS_FILE} entry ${index}: missing id`);
    if (!isStringList(entry.owns)) {
      throw new OwnsCheckConfigError(`${CARDS_FILE} entry ${index} (${id}): owns must be a list of paths`);
    }
    if (cards.has(id)) throw new OwnsCheckConfigError(`${CARDS_FILE}: duplicated card id ${id}`);
    cards.set(id, { id, owns: entry.owns });
  });
  return cards;
}

/**
 * Parses docs/plan/frozen-files.json: every entry needs a path and an editableBy list of known card ids.
 * @param {string} text
 * @param {Set<string>} knownCardIds
 * @returns {FrozenEntry[]}
 */
export function parseFrozenFiles(text, knownCardIds) {
  const data = parseJson(text, FROZEN_FILES_FILE);
  if (!Array.isArray(data)) throw new OwnsCheckConfigError(`${FROZEN_FILES_FILE}: expected a JSON array of entries`);
  return data.map((entry, index) => {
    const path = entry?.path;
    if (typeof path !== 'string' || path === '') {
      throw new OwnsCheckConfigError(`${FROZEN_FILES_FILE} entry ${index}: missing path`);
    }
    const where = `${FROZEN_FILES_FILE} entry ${index} (${path})`;
    if (!isStringList(entry.editableBy)) throw new OwnsCheckConfigError(`${where}: missing editableBy`);
    const unknown = entry.editableBy.find((/** @type {string} */ id) => !knownCardIds.has(id));
    if (unknown !== undefined) throw new OwnsCheckConfigError(`${where}: editableBy names unknown card ${unknown}`);
    return { path, editableBy: entry.editableBy };
  });
}

/**
 * Null when `after` only appends entries to the JSON array in `before`; otherwise the reason.
 * @param {string | null} before content at the merge-base (null: the file is new)
 * @param {string | null} after content at the head (null: the file was deleted)
 * @returns {string | null}
 */
export function appendOnlyViolation(before, after) {
  if (after === null) return 'deleted';
  /** @param {string} text */
  const parse = (text) => {
    try {
      const value = JSON.parse(text);
      return isStringList(value) && new Set(value).size === value.length ? value : null;
    } catch {
      return null;
    }
  };
  const next = parse(after);
  if (next === null) return 'not a JSON array of unique strings';
  if (before === null) return null;
  const previous = parse(before);
  if (previous === null) return 'the merge-base version is not a JSON array of unique strings';
  const kept = previous.length <= next.length && previous.every((entry, index) => next[index] === entry);
  return kept ? null : 'removes or reorders entries';
}

/**
 * Applies every owns-check rule to the files a branch changed.
 * @param {EvaluateInput} input
 * @returns {OwnsCheckResult}
 */
export function evaluate({ branch, changes, cards, frozen, readBefore, readAfter }) {
  const info = parseBranch(branch);
  if (info.kind === 'exempt') return { outcome: 'exempt', cardId: null, violations: [] };
  if (info.kind === 'invalid') {
    return {
      outcome: 'fail',
      cardId: null,
      violations: [`branch "${branch}" is not card/<id>-<slug>, renovate/… or opus/…`],
    };
  }
  const card = cards.get(info.cardId);
  if (card === undefined) {
    return {
      outcome: 'fail',
      cardId: info.cardId,
      violations: [`unknown card id ${info.cardId}: it is not in ${CARDS_FILE}`],
    };
  }
  /** @type {string[]} */
  const violations = [];
  for (const { path } of changes) {
    if (!card.owns.some((owned) => pathMatches(owned, path))) {
      violations.push(`outside owns: ${path}`);
      continue;
    }
    const lock = frozen.find((entry) => pathMatches(entry.path, path) && !entry.editableBy.includes(card.id));
    if (lock !== undefined) {
      const editors = lock.editableBy.length > 0 ? lock.editableBy.join(', ') : 'none';
      violations.push(`frozen: ${path} (frozen by ${lock.path}; editableBy: ${editors})`);
      continue;
    }
    if (APPEND_ONLY_FILES.includes(path)) {
      const reason = appendOnlyViolation(readBefore(path), readAfter(path));
      if (reason !== null) violations.push(`append-only: ${path} may only gain entries (${reason})`);
    }
  }
  return { outcome: violations.length > 0 ? 'fail' : 'pass', cardId: card.id, violations };
}
